name: "Tests and docs"

on:
  push:
  pull_request:

jobs:
  test-docs-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Sphinx & Dependencies
      run: pip install -e ".[all]"
    - name: Run tests
      run: pytest
    - name: Build Documentation
      run: cd "$GITHUB_WORKSPACE/docs" && make html
    - name: Build package
      run: python -m build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
